# Generated by Django 6.0.3 on 2026-03-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_car1', to='cars.car')),
                ('car_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_car2', to='cars.car')),
                ('car_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_car3', to='cars.car')),
            ],
            options={
                'unique_together': {('session_id',)},
            },
        ),
    ]
